### ISSUE TITLE
Getting Continuous Location Updates 

### ISSUE THREAD

**Issue by nidhinprathap** [david-serrano/locationprovider#4]
How can I get continuous location updates for an app? I went through the sample app and saw that locationRequestStopped() gets triggered after location is updated.

```
networkUpdatesListener = new LocationListener() {
                public void onLocationChanged(Location location) {
                    LocationProvider.this.outputLog("network returned");
                    LocationProvider.this.updateLocation((float)location.getLatitude(), (float)location.getLongitude());
                    if (LocationProvider.networkTimer != null) {
                        LocationProvider.networkTimer.cancel();
                    }

                    LocationProvider.this.removeUpdates(); 
                }

```

Why is removeUpdates Triggered here

**Comment by nidhinprathap** [comment]
any update????

**Comment by emailsubjekt** [comment]
Answer this man dude, this is important!

**Comment by david-serrano** [comment]
hi @nidhinprathap apologies for the massive delay in replying, i completely forgot this was an issue! The library is like this by design, it provides you with one location and then turns itself off, i would suggest for now you for the repo and remove this line if you need it, but i will add it as an improvement - something that can be passed through config
